# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CD

on:
  push:
  pull_request:
  schedule:
  - cron: "15 6 1 * *" # Every 2 weeks (15th) on 6:01
permissions:
  contents: read

jobs:
  Compile-and-Upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3.5.1
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Build
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        cache-disabled: true
        gradle-home-cache-cleanup: true
    - name: Install 7z
      run: sudo apt-get install 7zip -y
    - name: 7z Compression
      run: 7zz a -t7z -mx=9 immortality-fabric-build.7z ./build/libs/*.jar
    - name: Upload to Gofile
      run: ./.github/scripts/upload.sh immortality-fabric-build.7z
    - name: Clean Workspace
      run: rm -rf ./*
